# Generated by Django 4.2.30 on 2026-07-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(max_length=10)),
                ('doc_year', models.CharField(max_length=4)),
                ('doc_num', models.CharField(max_length=20)),
                ('doc_date', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_invoice', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('credit_fercility', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('secondary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('types', models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], default='Goods', max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('sub_family', models.CharField(blank=True, max_length=100)),
                ('shelf_no', models.CharField(blank=True, max_length=50)),
                ('supplier_item_code', models.CharField(blank=True, max_length=100)),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selling_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_products', to='automate1.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='automate1.supplier')),
                ('supplier_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='automate1.currency')),
                ('vat_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automate1.vat')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('warehouse', models.CharField(blank=True, max_length=255)),
                ('product_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product_unit', models.CharField(max_length=10)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='automate1.orderdocument')),
            ],
        ),
    ]
