# Generated by Django 4.1 on 2026-08-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
